### ISSUE TITLE
Data.py File issues 

### ISSUE THREAD

**Issue by hafsabatool587** [sustecher/StrokeSegmentation#1]
Getting issue in "Find_ranges" function.
 Min_z,Max_z,Min_x,Max_x,Min_y,Max_y=Find_ranges(label_array ,0,0)

Function is not defined in the data file.
 Thank you

**Comment by sustecher** [comment]
sorry, I forgot to upload the metric.py
you can find this function in metric.py 

def Find_ranges(mask,margin_xy,margin_z):
    #print(np.shape(mask))
    arr=np.nonzero(mask)
    Min_z=int(min(arr[0])-margin_z)
    Max_z=int(max(arr[0])+margin_z)

    Min_x=int(min(arr[1])-margin_xy)
    Max_x=int(max(arr[1])+margin_xy)
    Min_y=int(min(arr[2])-margin_xy)
    Max_y=int(max(arr[2])+margin_xy)
    
    Min_z=max(0,Min_z)
    Max_z=min(np.shape(mask)[0],Max_z)

    return Min_z,Max_z,Min_x,Max_x,Min_y,Max_y

************************************************************
This code is not only for this project, so there may some unuseful functions. Just ignore it.
Have fun!

**Comment by hafsabatool587** [comment]
Thank you so much :)
